version: '3'
services:
  web:
    image: "registry.gitlab.com/nunofacha/nunofacha.com"
    restart: "always"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    networks:
      - haproxy
      - default
networks:
  haproxy:
    external: true
